CREATE TABLE CREATORS (
    CreatorID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR2(255) NOT NULL,
    LastName VARCHAR2(255) NOT NULL,
    Email VARCHAR2(255) NOT NULL UNIQUE,
    HeadShotImage VARCHAR2(500),
    ProfileImage VARCHAR2(500),
    AboutMe VARCHAR2(2000),
    WorkExperience VARCHAR2(2000),
    Role VARCHAR2(255) NOT NULL,
    CreatedAt DATE DEFAULT SYSDATE,
    UpdatedAt DATE
);

CREATE TABLE CONTRIBUTORS (
    ContributorID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR2(255) NOT NULL,
    LastName VARCHAR2(255),
    Email VARCHAR2(255),
    Bio VARCHAR2(1000),
    ContributorType VARCHAR2(100),
    Website VARCHAR2(500),
    InstagramHandle VARCHAR2(100),
    CreatedAt DATE DEFAULT SYSDATE,
    UpdatedAt DATE
);

CREATE TABLE ISSUES (
    IssueID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Title VARCHAR2(255) NOT NULL,
    IssueNumber VARCHAR2(50),
    Theme VARCHAR2(255),
    Description VARCHAR2(2000),
    PublicationDate DATE,
    CoverImagePath VARCHAR2(500),
    Status VARCHAR2(50) DEFAULT 'Draft' NOT NULL,
    CreatedAt DATE DEFAULT SYSDATE,
    UpdatedAt DATE
);

CREATE TABLE ISSUE_CREATOR_CREDITS (
    IssueCreatorCreditID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IssueID NUMBER NOT NULL,
    CreatorID NUMBER NOT NULL,
    CreditRole VARCHAR2(255) NOT NULL,

    CONSTRAINT uq_issue_creator_role
        UNIQUE (IssueID, CreatorID, CreditRole),

    CONSTRAINT fk_issue_creator_credit_issue
        FOREIGN KEY (IssueID)
        REFERENCES ISSUES(IssueID),

    CONSTRAINT fk_issue_creator_credit_creator
        FOREIGN KEY (CreatorID)
        REFERENCES CREATORS(CreatorID)
);

CREATE TABLE ISSUE_CONTRIBUTOR_CREDITS (
    IssueContributorCreditID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IssueID NUMBER NOT NULL,
    ContributorID NUMBER NOT NULL,
    CreditRole VARCHAR2(255) NOT NULL,
    WorkTitle VARCHAR2(255),

    CONSTRAINT uq_issue_contributor_role
        UNIQUE (IssueID, ContributorID, CreditRole, WorkTitle),

    CONSTRAINT fk_issue_contributor_credit_issue
        FOREIGN KEY (IssueID)
        REFERENCES ISSUES(IssueID),

    CONSTRAINT fk_issue_contributor_credit_contributor
        FOREIGN KEY (ContributorID)
        REFERENCES CONTRIBUTORS(ContributorID)
);

CREATE TABLE PORTFOLIO_ITEMS (
    PortfolioItemID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CreatorID NUMBER NOT NULL,
    Title VARCHAR2(255) NOT NULL,
    Description VARCHAR2(2000),
    ImagePath VARCHAR2(500),
    MediaType VARCHAR2(100),
    YearCreated NUMBER(4),
    Role VARCHAR2(255),
    CreatedAt DATE DEFAULT SYSDATE,
    UpdatedAt DATE,

    CONSTRAINT fk_portfolio_creator
        FOREIGN KEY (CreatorID)
        REFERENCES CREATORS(CreatorID)
);

CREATE TABLE DIGITAL_FILES (
    DigitalFileID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IssueID NUMBER NOT NULL,
    FileName VARCHAR2(255),
    PdfPath VARCHAR2(500),
    FileSizeMB NUMBER(10,2),
    PageCount NUMBER,
    UploadedAt DATE DEFAULT SYSDATE,
    UpdatedAt DATE,

    CONSTRAINT uq_digital_file_issue
        UNIQUE (IssueID),

    CONSTRAINT fk_digital_file_issue
        FOREIGN KEY (IssueID)
        REFERENCES ISSUES(IssueID)
);

CREATE TABLE TAGS (
    TagID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TagName VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE ISSUE_TAGS (
    IssueID NUMBER NOT NULL,
    TagID NUMBER NOT NULL,

    CONSTRAINT pk_issue_tags
        PRIMARY KEY (IssueID, TagID),

    CONSTRAINT fk_issue_tags_issue
        FOREIGN KEY (IssueID)
        REFERENCES ISSUES(IssueID)
        ON DELETE CASCADE,

    CONSTRAINT fk_issue_tags_tag
        FOREIGN KEY (TagID)
        REFERENCES TAGS(TagID)
        ON DELETE CASCADE
);

CREATE TABLE PORTFOLIO_ITEM_TAGS (
    PortfolioItemID NUMBER NOT NULL,
    TagID NUMBER NOT NULL,

    CONSTRAINT pk_portfolio_item_tags
        PRIMARY KEY (PortfolioItemID, TagID),

    CONSTRAINT fk_portfolio_item_tags_item
        FOREIGN KEY (PortfolioItemID)
        REFERENCES PORTFOLIO_ITEMS(PortfolioItemID)
        ON DELETE CASCADE,

    CONSTRAINT fk_portfolio_item_tags_tag
        FOREIGN KEY (TagID)
        REFERENCES TAGS(TagID)
        ON DELETE CASCADE
);